openapi: 3.0.0
info:
  title: BFF Template
  description: >-
    # **BFF Template**


    ### This API provides a simplified interface for accessing _endpoints for_
    _`schemaNames`_ which `ProjectName` consumes.


    ### **It acts as a facade, hiding the complexity of the underlying services
    and providing a tailored interface for the frontend of the application.**


    ---


    > BFF comunicates with:


    - `API / Service Name`

    - `API / Service Name`

    - `API / Service Name`

    - `API / Service Name`

    - `API / Service Name`
        

    ---


    [Link to GitLab Repository](https://gitlab.com/plataforma-5/bff-template)


    ---


    ⠀⠀⠀⢠⣾⣷⣦⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀  

    ⠀⠀⣰⣿⣿⣿⣿⣷⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀  

    ⠀⢰⣿⣿⣿⣿⣿⣿⣷⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀  

    ⢀⣿⣿⣿⣿⣿⣿⣿⣿⣿⣷⣦⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀  

    ⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣷⣤⣀⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀  

    ⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣶⣤⣄⣀⣀⣤⣤⣶⣾⣿⣿⣿⡷  

    ⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡿⠁  

    ⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡿⠁⠀  

    ⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠏⠀⠀⠀  

    ⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠏⠀⠀⠀⠀  

    ⣿⣿⣿⡇⠀⡾⠻⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠁⠀⠀⠀⠀⠀  

    ⣿⣿⣿⣧⡀⠁⣀⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡇⠀⠀⠀⠀⠀⠀  

    ⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡟⠉⢹⠉⠙⣿⣿⣿⣿⣿⠀⠀⠀⠀⠀⠀⠀  

    ⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣷⣀⠀⣀⣼⣿⣿⣿⣿⡟⠀⠀⠀⠀⠀⠀⠀  

    ⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡿⠋⠀⠀⠀⠀⠀⠀⠀⠀  

    ⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡿⠛⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀  

    ⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡿⠛⠀⠤⢀⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀  

    ⣿⣿⣿⣿⠿⣿⣿⣿⣿⣿⣿⣿⠿⠋⢃⠈⠢⡁⠒⠄⡀⠈⠁⠀⠀⠀⠀⠀⠀⠀  

    ⣿⣿⠟⠁⠀⠀⠈⠉⠉⠁⠀⠀⠀⠀⠈⠆⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀  

    ⠋⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠘⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀


    ⢯⣿⣞⡷⣯⣟⣿⣳⣯⣟⣾⢯⣷⢯⣟⣯⣿⣽⣻⢯⣿⣻  

    ⣯⡿⣞⣿⣳⢿⣽⣻⡾⣯⣟⣷⢿⣽⣻⢾⣯⣟⡷⣿⣽⣻  

    ⣽⣻⠇⠀⠀⠀⠀⠀⠈⠙⢽⡾⣧⠀⠀⠀⠀⠀⠀⣿⣞⣷⣷  

    ⣻⣽⡇⠀⠀⣿⣟⣶⠄⠀⠈⣿⠇⠀⠀⣿⣟⣿⣻⢷⣻⡾⢷  

    ⣟⣾⡅⠀⠀⣿⣻⢾⠃⠀⠀⣿⠇⠀⠘⠁⠉⠈⠻⣻⣽⣟⢷  

    ⡿⣽⡆⠀⠀⠀⠀⠀⠀⣀⣼⡿⣶⢶⣴⡿⣆⠀⠀⢻⣳⣯⢷  

    ⢿⣯⠇⠀⠀⣷⣿⣻⣟⣯⡿⣽⠋⠛⢳⣿⡻⠀⠀⢸⣯⢷  

    ⣟⣾⡇⠀⠀⣿⣷⣻⣾⣽⣻⣽⣆⠀⠀⠉⠁⠀⣠⡿⣽⣻  

    ⢿⣞⣧⣤⣤⡿⣞⣷⣟⣾⣽⣳⣯⣷⡶⣴⡶⣾⢯⣟⡿⣽  

    ⢯⣿⣞⡷⣯⣟⣿⣳⣯⣟⣾⢯⣷⢯⣟⣯⣿⣽⣻⢯⣿⣻


    ---
  version: 1.0.0
servers:
  - url: http://localhost:5000
tags:
  - name: Example
    description: |-
      #### **This contains all** _**Example**_ **related requests**

      > Routes for _**example**_

      - `GET /example`
paths:
  /example:
    get:
      tags:
        - Example
      summary: Get example
      description: Get "Hello World" example from server
      responses:
        '200':
          description: OK
          headers:
            Content-Security-Policy:
              schema:
                type: string
                example: >-
                  default-src 'self';base-uri 'self';font-src 'self' https:
                  data:;form-action 'self';frame-ancestors 'self';img-src 'self'
                  data:;object-src 'none';script-src 'self';script-src-attr
                  'none';style-src 'self' https:
                  'unsafe-inline';upgrade-insecure-requests
            Cross-Origin-Embedder-Policy:
              schema:
                type: string
                example: require-corp
            Cross-Origin-Opener-Policy:
              schema:
                type: string
                example: same-origin
            Cross-Origin-Resource-Policy:
              schema:
                type: string
                example: same-origin
            X-DNS-Prefetch-Control:
              schema:
                type: string
                example: 'off'
            X-Frame-Options:
              schema:
                type: string
                example: SAMEORIGIN
            Strict-Transport-Security:
              schema:
                type: string
                example: max-age=15552000; includeSubDomains
            X-Download-Options:
              schema:
                type: string
                example: noopen
            X-Content-Type-Options:
              schema:
                type: string
                example: nosniff
            Origin-Agent-Cluster:
              schema:
                type: string
                example: '?1'
            X-Permitted-Cross-Domain-Policies:
              schema:
                type: string
                example: none
            Referrer-Policy:
              schema:
                type: string
                example: no-referrer
            X-XSS-Protection:
              schema:
                type: integer
                example: '0'
            Vary:
              schema:
                type: string
                example: Origin
            Access-Control-Allow-Credentials:
              schema:
                type: boolean
                example: 'true'
            Content-Type:
              schema:
                type: string
                example: application/json; charset=utf-8
            Content-Length:
              schema:
                type: integer
                example: '26'
            ETag:
              schema:
                type: string
                example: W/"1a-T7vCLEZV7pLSyUzkr9XBdG32YU8"
            Date:
              schema:
                type: string
                example: Thu, 15 Dec 2022 17:09:22 GMT
            Connection:
              schema:
                type: string
                example: keep-alive
            Keep-Alive:
              schema:
                type: string
                example: timeout=5
          content:
            application/json:
              schema:
                type: object
              example:
                message: Hello world!
    post:
      tags:
        - Example
      summary: Post example
      description: Returns the same body sent in request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                message: This is a testing example of post
                testing: true
      responses:
        '200':
          description: OK
          headers:
            Content-Security-Policy:
              schema:
                type: string
                example: >-
                  default-src 'self';base-uri 'self';font-src 'self' https:
                  data:;form-action 'self';frame-ancestors 'self';img-src 'self'
                  data:;object-src 'none';script-src 'self';script-src-attr
                  'none';style-src 'self' https:
                  'unsafe-inline';upgrade-insecure-requests
            Cross-Origin-Embedder-Policy:
              schema:
                type: string
                example: require-corp
            Cross-Origin-Opener-Policy:
              schema:
                type: string
                example: same-origin
            Cross-Origin-Resource-Policy:
              schema:
                type: string
                example: same-origin
            X-DNS-Prefetch-Control:
              schema:
                type: string
                example: 'off'
            X-Frame-Options:
              schema:
                type: string
                example: SAMEORIGIN
            Strict-Transport-Security:
              schema:
                type: string
                example: max-age=15552000; includeSubDomains
            X-Download-Options:
              schema:
                type: string
                example: noopen
            X-Content-Type-Options:
              schema:
                type: string
                example: nosniff
            Origin-Agent-Cluster:
              schema:
                type: string
                example: '?1'
            X-Permitted-Cross-Domain-Policies:
              schema:
                type: string
                example: none
            Referrer-Policy:
              schema:
                type: string
                example: no-referrer
            X-XSS-Protection:
              schema:
                type: integer
                example: '0'
            Vary:
              schema:
                type: string
                example: Origin
            Access-Control-Allow-Credentials:
              schema:
                type: boolean
                example: 'true'
            Content-Type:
              schema:
                type: string
                example: application/json; charset=utf-8
            Content-Length:
              schema:
                type: integer
                example: '71'
            ETag:
              schema:
                type: string
                example: W/"47-GxM6XagBY/ejlVSb7USg6eCbsQc"
            Date:
              schema:
                type: string
                example: Thu, 15 Dec 2022 17:12:36 GMT
            Connection:
              schema:
                type: string
                example: keep-alive
            Keep-Alive:
              schema:
                type: string
                example: timeout=5
          content:
            application/json:
              schema:
                type: object
              example:
                body:
                  message: This is a testing example of post
                  testing: true
